### ISSUE TITLE
parameters.py

### ISSUE THREAD

**Issue by WYH12342021** [vinPopulaire/MEC_offloading#11]
Hello, where do the loaded parameter data come from? The data generated by "LOAD_SAVED_PARAMETERS = Flase" can't be loaded normally, can you help me?

**Comment by vinPopulaire** [comment]
Hello! 
The `LOAD_SAVED_PARAMETERS` flag is used to load the parameters **_you have already_** created in order to run the simulation multiple times. This is done in order to keep the same configurations between runs and having the simulation run multiple times in order to eliminate the factor of randomness and generate aggregated results.
In order to generate the parameters to load, you have to first run the simulation once with `LOAD_SAVED_PARAMETERS = False` and `SAVE_PARAMETERS = True` in order to save the parameters in the `saved_runs/parameters/` path, and then again multiple times with `LOAD_SAVED_PARAMETERS = True` and `SAVE_PARAMETERS = False` to get the results.
