### ISSUE TITLE
How to generate test cases

### ISSUE THREAD

**Issue by cugjooker** [vinPopulaire/MEC_offloading#2]
when I run the simulation.py，terminal displays the following information：
1、
Repetition no: 1
Loading parameters
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~\Desktop\MEC_offloading-master\simulation.py in <module>
     50             infile = "saved_runs/parameters/" + case["users"] + "_" + case["servers"] + "_lr_" + "0.20"
     51
---> 52             with open(infile, 'rb') as in_strm:
     53                 params = dill.load(in_strm)
     54         else:

FileNotFoundError: [Errno 2] No such file or directory: 'saved_runs/parameters/hetero_hetero_lr_0.20'
2、
FileNotFoundError                         Traceback (most recent call last)
~\Desktop\MEC_offloading-master\generate_aggregated_results.py in <module>
     31     # infile = "/media/giorgos/My Passport/Programming/MEC offloading/parameters/" + key + "_lr_" + lr
     32     infile = "saved_runs/parameters/" + key + "_lr_" + lr
---> 33     with open(infile, 'rb') as in_strm:
     34         params = dill.load(in_strm)
     35

FileNotFoundError: [Errno 2] No such file or directory: 'saved_runs/parameters/hetero_hetero_lr_0.20'

could you tell me how to solve this problem？ Thank you very much！

![image](https://user-images.githubusercontent.com/57586560/70863663-59725d00-1f85-11ea-83ab-b2bdadd07d1f.png)
![image](https://user-images.githubusercontent.com/57586560/70863668-65f6b580-1f85-11ea-8102-888643ffbd93.png)

**Comment by vinPopulaire** [comment]
It seems like you are trying to load a parameters file even though you have not produced one yet.

You should go to parameters.py and change 
`LOAD_SAVED_PARAMETERS = False` 
in order to generate the new parameters that you set in the same file.

If you want to keep them in a file so you can later load them, just change 
`SAVE_PARAMETERS = True`
 Then the next time you run it if you want to use the same parameters you can change
`LOAD_SAVED_PARAMETERS = True`
