### ISSUE TITLE
Some problems encountered when running the code

### ISSUE THREAD

**Issue by cugjooker** [vinPopulaire/MEC_offloading#3]
when I run the plots_comparative.py，terminal displays the following information：
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~\Desktop\MEC_offloading-master\plots_comparative.py in <module>
     44     infile = "saved_runs/results/" + key + "_lr_" + "0.20"
     45
---> 46     with open(infile, 'rb') as in_strm:
     47         results[key] = dill.load(in_strm)
     48

FileNotFoundError: [Errno 2] No such file or directory: 'saved_runs/results/hetero_hetero_offload_dyn_lr_0.20'

could you tell me how to solve this problem？How to generate related files？Thank you very much！
![image](https://user-images.githubusercontent.com/57586560/71090456-03e4bd00-21de-11ea-84af-d2249a5b711c.png)

**Comment by vinPopulaire** [comment]
Similarly to #2 you still have not generated any results and you are trying to access not existent files. You should first run the simulations with your parameters and set
`SAVE_RESULTS = True` 
in the parameters.py file.

Even after you generate the results, they are not ready to be used in the `plot_comparative.py` script. Before using them you have to run the `generate_aggregated_results.py` so that you take all the repetitions and average them in order to remove the effects of randomness.

If you want to reproduce my results you have to set the parameters as described in my paper, generate all the files and when needed manually rename them as they are expected in `plot_comparative.py`.

If you want to plot your own results, just rename the input file name strings expected in the plot functions.
