### ISSUE TITLE
plots problem

### ISSUE THREAD

**Issue by Xuanzhihao** [vinPopulaire/MEC_offloading#4]
hi,I have some problem when i run create_plots.py, the output figure is too small. Do you know how to solve this problem?

![微信截图_20201120172808](https://user-images.githubusercontent.com/20358271/99783981-1b4ac980-2b56-11eb-8043-294b010ec65c.png)

**Comment by Xuanzhihao** [comment]
![微信截图_20201120172808](https://user-images.githubusercontent.com/20358271/99784205-6b299080-2b56-11eb-89ed-6f4fec8382ee.png)
![myplot](https://user-images.githubusercontent.com/20358271/99784243-7f6d8d80-2b56-11eb-886f-27622be01673.png)

**Comment by Xuanzhihao** [comment]
![image](https://user-images.githubusercontent.com/20358271/99802042-f19f9b80-2b71-11eb-8fff-9e8a8969052e.png)
![image](https://user-images.githubusercontent.com/20358271/99802055-f82e1300-2b71-11eb-9855-ef128f484ed1.png)
![image](https://user-images.githubusercontent.com/20358271/99802069-ff552100-2b71-11eb-94e4-352e0c6e43aa.png)
![image](https://user-images.githubusercontent.com/20358271/99802096-0b40e300-2b72-11eb-9934-d7266a70c268.png)
![image](https://user-images.githubusercontent.com/20358271/99802250-55c25f80-2b72-11eb-8a72-258b5e8076fa.png)

hi, i solve the problem by set ONE_FIGURE = False, but now the figure is not smooth and the server5 is over server1 in all figures, i don't change any parameters. Do you know the reason of it? Is any parameters should be changed? (hetero_hetrto_lr_0.20)

**Comment by vinPopulaire** [comment]
I'm not sure since I don't know how exactly you run your simulations but I'm gonna guess that maybe you run too few repetitions? Since users choose probabilistically the server to whom they will offload their data, they don't always converge to the same server. That's why I repeat the simulation a lot of times (repetition parameter) and get the aggregated results in the end, in order to reduce the "probabilistic" nature of the selection.
That would also explain the "not so smooth" figures you are getting, since the aggregated results would lead to smoother lines.

**Comment by Xuanzhihao** [comment]
the repetition number is 1000, same as the repetition number in github, is it enough? And I also notice that the time solt of the figure is 2000, but in the paper is 3000.

**Comment by vinPopulaire** [comment]
No the repetition number 1000 is enough. 
Maybe you generate new parameters in every repetition? The idea is to keep the same parameters in all repetitions so that the users and the servers have the same characteristics and only the probabilistic part changes between repetitions. 
You should set in `parameters.py`
`LOAD_SAVED_PARAMETERS = False`
`SAVE_PARAMETERS = True`
and run one repetition so that it saves the parameters.

Then you should set 
`LOAD_SAVED_PARAMETERS = True`
`SAVE_PARAMETERS = False`
and run the 1000 repetitions and generate the results.

**Comment by Xuanzhihao** [comment]
hi, I have successfully run the program, now I have a problrm with the system model: why the b* will become greater when the B_-u become greater? That means every user will offload all there data to the server. I tried to show the b when the users is homo and the servers is hetero, and then i found that all user's b is 1000.

**Comment by vinPopulaire** [comment]
> hi, I have successfully run the program, 

Glad to hear!

> now I have a problrm with the system model: why the b* will become greater when the B_-u become greater? 

That's expected since from Theorem 1 on the paper we can see that b* is linearly dependent on B_-u.

>That means every user will offload all there data to the server. I tried to show the b when the users is homo and the servers is hetero, and then i found that all user's b is 1000.

No that's not what it means. It means that users will choose to offload more data as the other users choose to offload more data. But from Theorem 1 we can see that b* mainly depends on user characteristics which in the case of homogeneous users, they are the same, and that's why all users' b* is the same. Now why it's 1000 (the maximum)? Because as you pointed, since it's linearly dependent on B_-u, the best response is for everyone to offload all their data to the server (we do mention that behavior in section 6.1.1). But that's not the case when there are heterogeneous users (Figure 4a). In this case, there are some users that send all of their data and all the others, due to their personal characteristics decide to offload part of their data, but still dependent on the B_-u. 

The problem with our model is that there will always be someone who offloads all his data and that is due to the functions used, so in your research you could always find a better way to model that in order to avoid this phenomenon!

**Comment by ZJier** [comment]
I've been fascinated by your research work lately. When I run the plots_comparative.py file, I always get: [Errno 2] No such file or directory: 'saved_runs/results/hetero_hetero_offload_dyn_lr_0.20'. 
However, none of the other files presented the problem.
It's worth noting that I followed the readme file, but I still can't get it to work, very much hope to get an answer, thank you~

**Comment by vinPopulaire** [comment]
If I'm not mistaken (since it's been some times since I wrote that code) the `hetero_hetero_offload_dyn_lr_0.20` is essentially the results of the dynamic approach. You have to manually rename the `hetero_hetero_offload_lr_0.02` produced when running the simulation with `CONSTANT PRICING` and `CONSTANT OFFLOADING` set to `False`.

Just a note, you have to run the simulation many times and get the aggregated results from `generate_aggregated_results.py` in order to reduce the randomness of the algorithm. Thus the `hetero_heter_offload_lr_0.02` you have to rename to "dyn" is produced [here](https://github.com/vinPopulaire/MEC_offloading/blob/c13776fd823082d424f5248a6baa707baae737e0/generate_aggregated_results.py#L121)
